name: PR Check
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        cache: 'pip'
    - name: Install PlatformIO
      run: pip install --upgrade platformio
    - name: Run tests on the embedded target
      env:
        PLATFORMIO_AUTH_TOKEN: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
      run: pio remote test -e hifive1-revb -v